import {
  FileText,
  Download,
  CalendarDays,
  BadgeCheck,
  AlertTriangle,
} from "lucide-react";

import Card from "../ui/Card";
import Button from "../ui/Button";
import InfoRow from "../ui/InfoRow";
import StatusBadge from "../ui/StatusBadge";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function InspectionReport({
  report = {},
}) {
  const {
    reportId = "REP-0001",
    inspectionDate = "-",
    complianceScore = 0,
    status = "pending",
    remarks = "No remarks available.",
  } = report;

  const downloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(255, 193, 7);
    doc.text("PPE Sentinel", 14, 20);

    doc.setFontSize(15);
    doc.setTextColor(40);
    doc.text("AI Construction Safety Inspection Report", 14, 30);

    autoTable(doc, {
      startY: 40,
      theme: "grid",
      head: [["Field", "Value"]],
      body: [
        ["Report ID", reportId],
        ["Inspection Date", inspectionDate],
        ["Compliance Score", `${complianceScore}%`],
        ["Inspection Status", status.toUpperCase()],
      ],
    });

    const remarksList =
      typeof remarks === "string"
        ? remarks.split(",").map((r) => r.trim())
        : [];

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 12,
      head: [["Inspector Remarks"]],
      body:
        remarksList.length > 0
          ? remarksList.map((r) => [r])
          : [["All workers are compliant."]],
    });

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      `Generated on ${new Date().toLocaleString()}`,
      14,
      doc.lastAutoTable.finalY + 18
    );

    doc.save(`${reportId}.pdf`);
  };
  const formattedRemarks =
  typeof remarks === "string"
    ? remarks
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean)
    : [];
  return (
    <Card
      title="Inspection Report"
      subtitle="Final inspection summary generated by the AI system."
    >
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <StatusBadge status={status} />

          <Button
            variant="primary"
            icon={<Download size={18} />}
            onClick={downloadPDF}
          >
            Download Report
          </Button>
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900">
          <InfoRow
            icon={<FileText size={16} />}
            label="Report ID"
            value={reportId}
          />

          <InfoRow
            icon={<CalendarDays size={16} />}
            label="Inspection Date"
            value={inspectionDate}
          />

          <InfoRow
            icon={<BadgeCheck size={16} />}
            label="Compliance Score"
            value={`${complianceScore}%`}
            valueColor="text-amber-400"
          />
        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-900 p-5">
          <h3 className="mb-3 text-lg font-semibold text-white">
            Inspector Remarks
          </h3>

          {formattedRemarks.length > 0 ? (
          <div className="space-y-3">
            {formattedRemarks.map((remark, index) => (
              <div
                key={index}
                className="flex items-start gap-3 rounded-lg border border-red-500/20 bg-red-500/5 p-3"
              >
                <AlertTriangle
                  size={18}
                  className="mt-0.5 text-red-400"
                />

                <span className="text-slate-300">
                  {remark}
                </span>
              </div>
            ))}
          </div>
        ) : (
          <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-3 text-emerald-400">
            ✅ All workers are compliant.
          </div>
        )}
        </div>
      </div>
    </Card>
  );
}